from . import forebet
from . import zulubet
from . import statarea
from . import predictz
from . import windrawwin
from . import scoutingstats
from . import vitibet
from . import afootballreport
from . import betclan
from . import freesupertips
from . import bettingclosed
from . import bzzoiro
