#!/usr/bin/env python3
"""Prune old dated telemetry from ``localdata/`` (bounded retention).

``localdata`` is committed by the daily workflow, and GitHub's directory view
stops listing entries after 1,000. Most of the growth is per-day telemetry
that nothing reads after its own day. This script removes those files once
they are older than the retention window (default 30 days) and leaves
everything else alone.

What is pruned (exact filename shapes only, see ``TELEMETRY_PATTERNS``):
  clv_report_DATE.md, clv_unmatched_DATE.json            CLV reports
  sent_ledger_DATE.json, shadow_sent_ledger_DATE.json,
  discovery_sent_ledger_DATE.json,
  notify_delivery_failures_DATE.json                     notification ledgers
  theoddsapi_attempts_DATE.json                          odds-attempt logs
  supabase_sync_manifest_DATE.json                       sync manifests
  official_run_DATE.json                                 official-run markers
  picks_DATE.txt                                         pick text reports
  picks_audit_DATE.md                                    pick audit display
  picks_morning_DATE.json                                pick morning files,
                                                         ONLY when redundant

Each reader of these families was checked: all of them read only the current
run date (dedup ledgers, attempt blocks, run markers) or only write the file
(reports, manifests). The edge-firing tripwire reads morning files within 14
days, inside the 30-day window.

``picks_morning_DATE.json`` is not display-only. The rolling audit
(``audit_recent_picks.load_archived_picks_with_receipt``) uses it as the
immutable morning baseline and falls back to ``picks_DATE.json`` when it is
missing. On dates where the regular ledger was later overwritten, the morning
file is the only faithful record. So a morning file is pruned only when the
audit loader gives byte-identical output for that date without it. Anything
else is kept.

Deliberately retained, with no age limit:
  picks_DATE.json            durable replay/audit archive (replay parity input)
  auto_tickets_DATE.txt      printed slips; seed_slice_ledger() rebuilds the
                             selection-ladder evidence from them
  rolling ledgers/state, monthly source archives (*_YYYY-MM.csv.gz),
  warehouse data, and any file whose name does not match a known pattern.

Unknown files are never deleted. Retaining every daily pick archive means
``localdata`` still grows by about 2 entries per day (picks_DATE.json and
auto_tickets_DATE.txt) plus non-redundant morning files. That growth is linear
but slow; compacting those archives would need the replay/audit loaders to
read a new format first.

Usage::

    python scripts/clean_localdata.py                  # keep the latest 30 days
    python scripts/clean_localdata.py --keep-days 14
    python scripts/clean_localdata.py --dry-run        # list, delete nothing
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
import tempfile
from datetime import date, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LOCALDATA = ROOT / "localdata"
DEFAULT_KEEP_DAYS = 30

_DATE = r"(?P<day>20\d{2}-\d{2}-\d{2})"

# Exact shapes. A new file family is kept until it is added here on purpose.
TELEMETRY_PATTERNS: tuple[re.Pattern[str], ...] = tuple(
    re.compile(p)
    for p in (
        rf"^clv_report_{_DATE}\.md$",
        rf"^clv_unmatched_{_DATE}\.json$",
        rf"^sent_ledger_{_DATE}\.json$",
        rf"^shadow_sent_ledger_{_DATE}\.json$",
        rf"^discovery_sent_ledger_{_DATE}\.json$",
        rf"^notify_delivery_failures_{_DATE}\.json$",
        rf"^theoddsapi_attempts_{_DATE}\.json$",
        rf"^supabase_sync_manifest_{_DATE}\.json$",
        rf"^official_run_{_DATE}\.json$",
        rf"^picks_{_DATE}\.txt$",
        rf"^picks_audit_{_DATE}\.md$",
        rf"^source_settlement_coverage_{_DATE}\.json$",
        rf"^source_settlement_coverage_{_DATE}\.md$",
        rf"^source_funnel_{_DATE}\.json$",
        rf"^source_funnel_{_DATE}\.md$",
        rf"^shadow_candidates_{_DATE}\.json$",
        rf"^shadow_candidates_{_DATE}\.md$",
    )
)

# ``--policy fresh_production`` prefixes. These are all regenerated by a run
# of the lane from raw evidence, so an old copy is provably reconstructible.
# Raw captures, settled overlays, warehouse inputs, alias/entity registries,
# source code, tests, Config/ and HANDOVER.md are NOT in this list and can
# never be selected by this policy.
# (prefix, allowed extensions). Every one of these is fully regenerated by a
# run of the pipeline from raw evidence, so an old copy is reconstructible.
FRESH_PRODUCTION_PREFIXES: tuple[tuple[str, tuple[str, ...]], ...] = (
    # fresh_production lane artifacts
    ("fresh_production_walkforward", ("json", "md")),
    ("fresh_production_certified_edges", ("json", "md")),
    ("fresh_production_candidate_picks", ("json", "md")),
    ("fresh_production_dispatchable_picks", ("json", "md")),
    ("fresh_production_production_picks", ("json",)),
    ("source_health", ("json", "md")),
    ("model_health", ("json", "md")),
    ("artifact_manifest", ("json", "md")),
    # audit/diagnostic reports
    ("source_funnel", ("json", "md")),
    ("shadow_candidates", ("json", "md")),
    ("source_settlement_coverage", ("json", "md")),
    ("clv_report", ("md",)),
    ("clv_unmatched", ("json",)),
    ("picks_audit", ("md",)),
    ("official_run", ("json",)),
    ("supabase_sync_manifest", ("json",)),
    ("theoddsapi_attempts", ("json",)),
    ("notify_delivery_failures", ("json",)),
    ("ml_fade_checkpoint_contexts", ("txt",)),
    ("ml_fade_checkpoint_price_study", ("txt",)),
    ("ml_fade_research_report", ("md",)),
    # display-only rendering of a durable archive (picks_DATE.json is kept)
    ("picks", ("txt",)),
)
# NOTE: auto_tickets_DATE.txt is deliberately absent. seed_slice_ledger()
# rebuilds the selection-ladder evidence from those slips, so they are
# evidence, not a report, and this policy must never touch them.

# Notification dedupe ledgers. Pruning one older than the window is safe
# because the notifier only ever consults the current run date, but they are
# listed separately so the manifest can say why they were eligible.
NOTIFICATION_LEDGER_PREFIXES: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("sent_ledger", ("json",)),
    ("shadow_sent_ledger", ("json",)),
    ("discovery_sent_ledger", ("json",)),
)

# Never pruned by this policy, whatever their age. Listed for the manifest.
PROTECTED_DESCRIPTIONS: tuple[str, ...] = (
    ".git/ and all version history",
    "source code, tests, Config/, HANDOVER.md",
    "raw source captures (*.csv.gz, monthly archives)",
    "settled result overlays (settled_results.json)",
    "warehouse inputs and rolling state/ledger files",
    "alias and entity registries (team_aliases.json, registries)",
    "durable pick archives (picks_DATE.json, picks_morning_DATE.json)",
    "the current target date's artifacts",
    "the newest N dates for every generated prefix",
    "any file whose name does not match a known generated prefix",
)

_ALL_PREFIXES = FRESH_PRODUCTION_PREFIXES + NOTIFICATION_LEDGER_PREFIXES

FRESH_PRODUCTION_PATTERNS: tuple[tuple[str, re.Pattern[str]], ...] = tuple(
    (prefix, re.compile(
        rf"^{re.escape(prefix)}_{_DATE}\.(?:{'|'.join(exts)})$"))
    for prefix, exts in _ALL_PREFIXES
)

DEFAULT_KEEP_LATEST = 3

# Pure per-day diagnostics that no reader consults after their own run date.
# Each was checked: they are written once and only ever read for "today".
# A tighter window here is where the real size reduction comes from.
SHORT_WINDOW_DAYS = 7
SHORT_WINDOW_PREFIXES: frozenset[str] = frozenset({
    "theoddsapi_attempts",
    "clv_unmatched",
    "notify_delivery_failures",
    "supabase_sync_manifest",
    "ml_fade_checkpoint_contexts",
    "ml_fade_checkpoint_price_study",
    "official_run",
})

# Pruned only after the audit-parity proof in ``morning_archive_is_redundant``.
MORNING_PATTERN = re.compile(rf"^picks_morning_{_DATE}\.json$")


def _file_day(pattern: re.Pattern[str], name: str) -> date | None:
    match = pattern.match(name)
    if not match:
        return None
    try:
        return date.fromisoformat(match.group("day"))
    except ValueError:
        return None  # malformed date-shaped name: not safe to classify


def _telemetry_day(name: str) -> date | None:
    for pattern in TELEMETRY_PATTERNS:
        day = _file_day(pattern, name)
        if day is not None:
            return day
    return None


def classify_fresh_production(name: str) -> tuple[str, date] | None:
    """Return ``(prefix, day)`` when ``name`` is a known generated artifact.

    Anything that does not match exactly returns ``None`` and is therefore
    never a deletion candidate.
    """
    for prefix, pattern in FRESH_PRODUCTION_PATTERNS:
        day = _file_day(pattern, name)
        if day is not None:
            return prefix, day
    return None


def fresh_production_files_to_prune(
    root: Path = LOCALDATA,
    *,
    keep_days: int = DEFAULT_KEEP_DAYS,
    keep_latest: int = DEFAULT_KEEP_LATEST,
    today: date | None = None,
    target_date: date | None = None,
) -> list[Path]:
    """Stale generated artifacts only. See ``fresh_production_retention_plan``."""
    plan = fresh_production_retention_plan(
        root, keep_days=keep_days, keep_latest=keep_latest, today=today,
        target_date=target_date)
    return [entry["path"] for entry in plan["delete"]]


def fresh_production_retention_plan(
    root: Path = LOCALDATA,
    *,
    keep_days: int = DEFAULT_KEEP_DAYS,
    keep_latest: int = DEFAULT_KEEP_LATEST,
    today: date | None = None,
    target_date: date | None = None,
) -> dict:
    """Decide, with a written reason, what to delete and what to keep.

    Retention, evaluated in this order — the first rule that fires wins and
    is recorded as the reason:

    1. the name matches no known generated prefix -> keep (unmatched);
    2. the date is the current target date -> keep;
    3. the date is one of the newest ``keep_latest`` for its prefix -> keep;
    4. the date is within the last ``keep_days`` days -> keep;
    5. otherwise -> delete (stale, regenerable from raw evidence).

    Raw captures, settled overlays, registries, durable pick archives and
    source code all fail rule 1, so they are structurally unreachable here.
    """
    if keep_days < 1:
        raise ValueError("keep_days must be at least 1")
    if keep_latest < 0:
        raise ValueError("keep_latest must not be negative")
    root = Path(root)
    today = today or date.today()
    cutoff = today - timedelta(days=keep_days - 1)
    protected_day = target_date or today

    matched: list[tuple[str, date, Path]] = []
    unmatched: list[Path] = []
    for path in sorted(root.iterdir()) if root.exists() else ():
        if not path.is_file() or path.is_symlink():
            continue
        hit = classify_fresh_production(path.name)
        if hit is None:
            unmatched.append(path)
            continue
        matched.append((hit[0], hit[1], path))

    newest_per_prefix: dict[str, set[date]] = {}
    for prefix in {prefix for prefix, _day, _path in matched}:
        days = {day for p, day, _path in matched if p == prefix}
        newest_per_prefix[prefix] = set(sorted(days, reverse=True)[:keep_latest])

    delete: list[dict] = []
    keep: list[dict] = []
    for prefix, day, path in matched:
        size = path.stat().st_size if path.exists() else 0
        entry = {"path": path, "file": path.name, "prefix": prefix,
                 "day": day.isoformat(), "bytes": size}
        if day == protected_day:
            keep.append({**entry, "reason": "current_target_date"})
        elif day in newest_per_prefix[prefix]:
            keep.append({**entry, "reason": f"within_newest_{keep_latest}_for_prefix"})
        else:
            window = (min(keep_days, SHORT_WINDOW_DAYS)
                      if prefix in SHORT_WINDOW_PREFIXES else keep_days)
            prefix_cutoff = (today - timedelta(days=window - 1)
                             if window != keep_days else cutoff)
            if day >= prefix_cutoff:
                keep.append({**entry, "reason": f"within_last_{window}_days"})
            else:
                delete.append({**entry,
                               "reason": f"stale_generated_artifact_older_than_"
                                         f"{window}_days_and_outside_newest_"
                                         f"{keep_latest}"})

    by_prefix: dict[str, int] = {}
    for prefix, _day, path in matched:
        by_prefix[prefix] = by_prefix.get(prefix, 0) + (
            path.stat().st_size if path.exists() else 0)

    return {
        "delete": delete,
        "keep": keep,
        "unmatched": unmatched,
        "files_considered": len(matched) + len(unmatched),
        "generated_files_matched": len(matched),
        "unmatched_files_left_alone": len(unmatched),
        "largest_generated_files": sorted(
            ({"file": e["file"], "bytes": e["bytes"]} for e in delete + keep),
            key=lambda item: -item["bytes"])[:10],
        "largest_generated_prefixes": sorted(
            ({"prefix": k, "bytes": v} for k, v in by_prefix.items()),
            key=lambda item: -item["bytes"])[:10],
        "keep_days": keep_days,
        "keep_latest": keep_latest,
        "today": today.isoformat(),
        "target_date": protected_day.isoformat(),
    }


def write_artifact_manifest(plan: dict, *, root: Path, dry_run: bool) -> tuple[Path, Path]:
    """Record what the retention policy removed, what it kept, and why."""
    today = plan["today"]
    deleted = plan["delete"]
    total = sum(e["bytes"] for e in deleted)
    kept_reasons: dict[str, int] = {}
    for entry in plan["keep"]:
        kept_reasons[entry["reason"]] = kept_reasons.get(entry["reason"], 0) + 1

    payload = {
        "schema": 2,
        "policy": "fresh_production",
        "generated": today,
        "dry_run": dry_run,
        "keep_days": plan["keep_days"],
        "keep_latest": plan["keep_latest"],
        "target_date": plan["target_date"],
        "files_considered": plan["files_considered"],
        "files_deleted": len(deleted),
        "bytes_deleted": total,
        "why_each_deleted": [
            {"file": e["file"], "prefix": e["prefix"], "bytes": e["bytes"],
             "reason": e["reason"]} for e in deleted],
        "why_each_kept": [
            {"file": e["file"], "prefix": e["prefix"], "reason": e["reason"]}
            for e in plan["keep"]],
        "kept_reason_counts": kept_reasons,
        "raw_evidence_preserved": list(PROTECTED_DESCRIPTIONS),
        "unmatched_files_left_alone": plan["unmatched_files_left_alone"],
        "largest_generated_files": plan["largest_generated_files"],
        "largest_generated_prefixes": plan["largest_generated_prefixes"],
        "known_prefixes": [prefix for prefix, _exts in _ALL_PREFIXES],
        "no_files_removed_explanation": (
            None if deleted else
            "Nothing was old enough: every matched generated artifact is either "
            "the current target date, inside the newest-per-prefix window, or "
            "within the retention window. Unmatched files are never eligible."
        ),
    }
    json_path = root / f"artifact_manifest_{today}.json"
    md_path = root / f"artifact_manifest_{today}.md"
    json_path.write_text(json.dumps(payload, indent=2, sort_keys=True))

    lines = [
        f"# artifact_manifest — data_retention — {today}",
        "",
        f"- policy: `fresh_production` (keep-days {plan['keep_days']}, "
        f"keep-latest {plan['keep_latest']}, target date {plan['target_date']})",
        f"- files considered: {payload['files_considered']}",
        f"- files deleted: {payload['files_deleted']}",
        f"- bytes deleted: {payload['bytes_deleted']}",
        f"- unmatched files left alone: {payload['unmatched_files_left_alone']}",
        f"- dry run: {'yes' if dry_run else 'no'}",
        "",
    ]
    if payload["no_files_removed_explanation"]:
        lines += ["## Why nothing was removed", "",
                  payload["no_files_removed_explanation"], ""]
    else:
        lines += ["## Deleted", "", "| file | prefix | bytes | reason |",
                  "|---|---|---:|---|"]
        lines += [f"| {e['file']} | {e['prefix']} | {e['bytes']} | {e['reason']} |"
                  for e in deleted]
        lines.append("")
    lines += ["## Kept (by reason)", "", "| reason | files |", "|---|---:|"]
    lines += [f"| {reason} | {count} |" for reason, count in sorted(kept_reasons.items())]
    lines += ["", "## Largest generated prefixes", "", "| prefix | bytes |", "|---|---:|"]
    lines += [f"| {e['prefix']} | {e['bytes']} |"
              for e in plan["largest_generated_prefixes"]]
    lines += ["", "## Never eligible for deletion", ""]
    lines += [f"- {item}" for item in PROTECTED_DESCRIPTIONS]
    lines.append("")
    md_path.write_text("\n".join(lines))
    return json_path, md_path


def _audit_loader():
    scripts_dir = str(Path(__file__).resolve().parent)
    if scripts_dir not in sys.path:
        sys.path.insert(0, scripts_dir)
    import audit_recent_picks  # noqa: PLC0415 - lazy: only needed for morning files

    return audit_recent_picks.load_archived_picks_with_receipt


def morning_archive_is_redundant(root: Path, day: str) -> bool:
    """True only if deleting ``picks_morning_{day}.json`` changes nothing.

    Runs the audit's own loader for ``day`` twice: once on ``root`` and once
    on a scratch directory holding only the regular ``picks_{day}.json``.
    Byte-identical output means the audit (and every morning-file reader)
    loses no information. Any failure counts as "not redundant".
    """
    try:
        loader = _audit_loader()
        with_morning, _ = loader(day, day, localdata=root)
        with tempfile.TemporaryDirectory() as scratch:
            regular = root / f"picks_{day}.json"
            if regular.exists():
                shutil.copy2(regular, Path(scratch) / regular.name)
            without_morning, _ = loader(day, day, localdata=Path(scratch))
    except Exception as exc:  # fail closed: keep the file
        print(f"  keeping picks_morning_{day}.json (parity check failed: {exc})")
        return False

    def dump(rows):
        return json.dumps(rows, sort_keys=True, ensure_ascii=False, default=str)

    return dump(with_morning) == dump(without_morning)


def files_to_prune(
    root: Path = LOCALDATA,
    *,
    keep_days: int = DEFAULT_KEEP_DAYS,
    today: date | None = None,
) -> list[Path]:
    """Return old known telemetry files; never unknown or durable data."""
    if keep_days < 1:
        raise ValueError("keep_days must be at least 1")
    root = Path(root)
    today = today or date.today()
    cutoff = today - timedelta(days=keep_days - 1)  # oldest retained day
    stale: list[Path] = []
    for path in sorted(root.iterdir()) if root.exists() else ():
        if not path.is_file() or path.is_symlink():
            continue
        day = _telemetry_day(path.name)
        if day is not None:
            if day < cutoff:
                stale.append(path)
            continue
        morning_day = _file_day(MORNING_PATTERN, path.name)
        if (morning_day is not None and morning_day < cutoff
                and morning_archive_is_redundant(root, morning_day.isoformat())):
            stale.append(path)
    return stale


def clean_localdata(
    root: Path = LOCALDATA,
    *,
    keep_days: int = DEFAULT_KEEP_DAYS,
    today: date | None = None,
    dry_run: bool = False,
) -> list[Path]:
    """Delete (or with ``dry_run`` only list) stale telemetry; return paths."""
    removed = files_to_prune(root, keep_days=keep_days, today=today)
    for path in removed:
        print(f"  {'would remove' if dry_run else 'removing'} stale telemetry: {path.name}")
        if not dry_run:
            path.unlink()
    return removed


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Prune old dated telemetry from localdata/ (bounded retention).")
    parser.add_argument("--keep-days", type=int, default=DEFAULT_KEEP_DAYS,
                        help=f"recent calendar days to retain (default: {DEFAULT_KEEP_DAYS})")
    parser.add_argument("--today", type=date.fromisoformat, default=None,
                        help="reference date YYYY-MM-DD (default: today)")
    parser.add_argument("--localdata", type=Path, default=LOCALDATA,
                        help="directory to clean (default: repo localdata/)")
    parser.add_argument("--dry-run", action="store_true",
                        help="list what would be removed without deleting")
    parser.add_argument("--policy", choices=("telemetry", "fresh_production"),
                        default="telemetry",
                        help="retention policy to apply (default: telemetry)")
    parser.add_argument("--keep-latest", type=int, default=DEFAULT_KEEP_LATEST,
                        help="fresh_production: newest dates kept per prefix regardless of age")
    parser.add_argument("--target-date", type=date.fromisoformat, default=None,
                        help="fresh_production: current target date, never pruned")
    parser.add_argument("--write-manifest", action="store_true",
                        help="fresh_production: write artifact_manifest_DATE.{json,md}")
    args = parser.parse_args(argv)

    if args.policy == "fresh_production":
        today = args.today or date.today()
        print(f"Applying data_retention policy 'fresh_production' "
              f"(keep-days {args.keep_days}, keep-latest {args.keep_latest}) ...")
        plan = fresh_production_retention_plan(
            args.localdata, keep_days=args.keep_days, keep_latest=args.keep_latest,
            today=today, target_date=args.target_date)
        total = sum(e["bytes"] for e in plan["delete"])
        for entry in plan["delete"]:
            print(f"  {'would remove' if args.dry_run else 'removing'} "
                  f"stale generated artifact: {entry['file']} ({entry['bytes']} B)")
            if not args.dry_run:
                entry["path"].unlink()
        if args.write_manifest:
            json_path, md_path = write_artifact_manifest(
                plan, root=args.localdata, dry_run=args.dry_run)
            print(f"  manifest: {json_path.name}, {md_path.name}")
        verb = "Would remove" if args.dry_run else "Removed"
        print(f"Done. {verb} {len(plan['delete'])} file(s), {total} byte(s); "
              f"considered {plan['files_considered']}, left "
              f"{plan['unmatched_files_left_alone']} unmatched file(s) alone.")
        if not plan["delete"]:
            print("  nothing was stale: everything matched is current, inside the "
                  "newest-per-prefix window, or within the retention window.")
        return 0

    print(f"Cleaning dated localdata telemetry (keeping {args.keep_days} days) ...")
    removed = clean_localdata(args.localdata, keep_days=args.keep_days,
                              today=args.today, dry_run=args.dry_run)
    remaining = sum(1 for _ in args.localdata.iterdir()) if args.localdata.exists() else 0
    verb = "Would remove" if args.dry_run else "Removed"
    print(f"Done. {verb} {len(removed)} file(s); {remaining} entries in {args.localdata.name}/.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
